name: notify

on:
  push:
    branches:
      - main
    paths:
      - data/**
      - diff.py
      - .github/workflows/notify.yaml

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: '3.11'

      - run: pip install -r bs/requirements.txt

      - name: notify
        run: ls data/*/*/*/* | tail -n 2 | xargs python diff.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

