name: Wireguard

on:
  pull_request:
  workflow_dispatch:

jobs:
  wireguard:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wireguard
      - run: echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}" > privatekey
      - run: echo "${{ secrets.WIREGUARD_PRESHARED_KEY }}" > presharedkey
      - run: ls -l privatekey presharedkey
      - run: sudo ip link add dev wg0 type wireguard
      #- run: sudo ip address add dev wg0 10.220.182.9/24
      - run: sudo ip address add dev wg0 10.220.182.9/24 peer 10.220.182.1/24
      - run: sudo wg set wg0 listen-port 48123 private-key privatekey peer /lLsdb8Rco38DbSxtt2SiMI/uxeTkSrJY+CpkuzGJkE= preshared-key presharedkey allowed-ips 0.0.0.0/0 endpoint decoboco.tplinkdns.com:51820
      #- run: sudo wg set wg0 private-key privatekey peer /lLsdb8Rco38DbSxtt2SiMI/uxeTkSrJY+CpkuzGJkE= preshared-key presharedkey allowed-ips 0.0.0.0/0 endpoint decoboco.tplinkdns.com:51820
      - run: sudo ip link set up dev wg0
      - run: ip a s
      - run: ip r
      - run: sudo wg
      - run: ping 10.220.182.1
      - run: curl -vvv --connect-timeout 5 -m 10 http://192.168.210.107/
