name: Wireguard

on:
  workflow_dispatch:

jobs:
  wireguard:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install wireguard
      - run: echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}" > privatekey
      - run: sudo ip link add dev wg0 type wireguard
      - run: sudo ip address add dev wg0 10.220.182.9 peer 10.220.182.1
      - run: sudo wg set wg0 listen-port 48123 private-key privatekey peer /lLsdb8Rco38DbSxtt2SiMI/uxeTkSrJY+CpkuzGJkE= allowed-ips 0.0.0.0/0 endpoint decoboco.tplinkdns.com:51820
      - run: sudo ip link set up dev wg0
      - run: curl -vvv http://192.168.210.107/
